name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PASS }}
        port: 4444
        script: |
            cd /home/magangjesicabkfe
            git pull
            git status
            cd /home
            cp -r magangjesicabkfe /var/www/html/
            cd /var/www/html/magangjesicabkfe
            npm install
            npm run build
